# Numpy - DERS-2

# Array Elemanlarına Erişim 

**Array'lerde her elemanın bir index numarası vardır.
   Index numarası ilk eleman için 0 'dır. 
   0 ile başlayıp 1' er artarak devam eder.
   Array'in elemanlarına bu index numarası ile erişilebilir.**

**Syntax :**
****
**array_ismi [ index_numarası ]**

In [84]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print( arr[0], arr[1] )

1 2


In [85]:
arr[2]

3

**List yapısından farklı olarak NumPy Array'lerde multi-indexing yapılabilir.
  Yani belirli index numaralarındaki birden fazla elemanı tek seferde getirme işlemi yapabiliriz, 
  ancak sonuç yine bir array olarak gelir. Syntax da farklıdır :**
****
         

**array_ismi [ [ array_num, array_num, array_num ] ]**

In [88]:
print( arr[ [2, 5, 1] ] )

[3 6 2]


# Negative Indexing (Negatif Indexleme)

**Array'lerde ilk elemandan son elemana doğru (soldan sağa) index numaraları 0, 1, 2, 3...
 şeklinde gitmektedir.**
    

**Eğer sağdan sola gelmek istersek index -1 ile başlar -2, -3, -4.... şeklinde devam eder.
  Buna negative indexing denilir.
  Ayrıca bu şekilde array'in son elemanına doğrudan -1 index numarası ile erişilebilir.**

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr[-1]

7

In [3]:
arr[-2]

6

# Temel Array Türleri

****
**0-D Arrays**

In [19]:
import numpy as np

arr = np.array(42)

print(arr)

42


****
**1-D Arrays**

**0-D Array'leri elemanları olarak alan array'lerdir.
  Tek-boyutlu ya da 1-D Array olarak adlandırılırlar.**

In [ ]:
import numpy as np

In [21]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


**1-D Array Elemanlarına Erişim :**

In [36]:
arr[2]

3

In [35]:
print( "\n", arr[0], "\n", arr[1], "\n", arr[2], "\n", arr[-1] )


 1 
 2 
 3 
 5


****
**2-D Arrays**

**1-D Array'leri elemanları olarak alan array'lerdir.**

In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


**2-D Array Elemanlarına Erişim :**

**2 boyutlu array'leri satır ve sütunlara sahip bir tablo olarak düşünebiliriz.**

In [42]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('1.satırın 2. elemanı : ', arr[0, 1])

1.satırın 2. elemanı :  2


**1. satırın index numarası 0, 2. elemanın index numarası 1 olacağı için
  arr[0, 1] yapılır.**

In [44]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2.satırın 5.elemanı : ', arr[1, 4])

2.satırın 5.elemanı :  10


****
**3-D Arrays**

**2-D (2 boyutlu) Array'leri elemanları olarak alan array'lerdir.**

In [45]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


**3-D Array Elemanlarına Erişim :**

In [46]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


**AÇIKLAMA  :**

**Burada ; array'i  arr[a, b] şeklinde düşünelim.**

**a elemanı = [ [1, 2, 3], [4, 5, 6] ]**
              

**b elemanı = [ [7, 8, 9],  [10, 11, 12] ]**

**arr[0, 1, 2] ifadesinde girdiğimiz ilk index numarası array'imizi arr[a, b] şeklinde düşünürsek
bu arrayde a ve b elemanlarından hangisi olduğunu seçer. 0 girdiğimiz için a'yı seçtik.**

**arr[0, 1, 2] ifadesinde girdiğimiz ikinci index numarası ;**

**a elemanında hangi eleman olduğunu seçer. 
  Girilen index num. 1 olduğu için a elemanında 1 index numaralı elemana yani;**

**ikinci eleman olan [4, 5, 6] array'ine gider.**

**arr[0, 1, 2] ifadesinde girdiğimiz üçüncü index numarası ;**

**[4, 5, 6] array'inde hangi elemana gideceğini seçer.
arr[0, 1, 2] bu index num. 2 olduğu için ;**

**[4, 5, 6] arrayinde 2 numaralı index'te "6" integer sayısı bulunuyor.**

**Böylece [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] arrayinde;**

**arr[0, 1, 2] sonucu "6" olur.**

****
# Array'lerde Axis Nedir ?


<img src="numpy_arrays_axis.png">

****
# Array'ler Üzerinde Değişiklik Yapma 
 ## Eleman Ekleme ve Silme

****
### append( ) Methodu ile Array'e Eleman ekleme

__Bir array'in sonuna değerler/elemanlar eklemeyi sağlar.__

__Zorunlu parametreleri ; array ve values(eklenecek değerler)__ 

In [559]:
arr= np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

print(arr)

[1 2 3 4 5 6 7 8 9]


In [138]:
# axis parametresi opsiyoneldir.
# axis Default olarak alınırsa; flattened(düzleştirilmiş-tek-boyutlu halde) bir array üretilir.

import numpy as np

arr = np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]])

print(arr)

[1 2 3 4 5 6 7 8 9]


In [5]:

arr = np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:

a = np.array([[1,2,3],[4,5,6]]) 
a = np.append(a, [7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [12]:

b = np.array([[1,2,3],[4,5,6]]) 

print("Orjinal array : \n", b, "\n")

b = np.append(b, [[7,8,9]], axis=0)

print("Yeni array : \n", b)

Orjinal array : 
 [[1 2 3]
 [4 5 6]] 

Yeni array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:


b = np.array([[1,2,3],[4,5,6]]) 

print("Orjinal array : \n", b, "\n")

b = np.append(b, [[5,5,5],[7,8,9]], axis = 1)

print("Yeni array : \n", b)

Orjinal array : 
 [[1 2 3]
 [4 5 6]] 

Yeni array : 
 [[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


****
### insert( ) Methodu ile Array'e Eleman Ekleme

__Zorunlu parametreleri ; array, obj ve eklenecek_değerler__  
__obj parametresine ekleme yapılacak indexler girilir.__  

__axis parametresi opsiyoneldir.__  
__Default olarak; flattened(düzleştirilmiş-tek-boyutlu halde) bir array üretilir.__  
__Axis default haldeyken eleman ekleme yapılırken de indexler tek-boyutlu array halinde düşünülür.__  

In [67]:
arr = np.array([2, 3, 4, 5, 6, 7])

np.insert(arr, 2, 9)

array([2, 3, 9, 4, 5, 6, 7])

In [68]:

a = np.array([[1, 1], [2, 2], [3, 3]])

print(a)

[[1 1]
 [2 2]
 [3 3]]


array([1, 5, 1, 2, 2, 3, 3])

In [70]:
np.insert(a, 1, 5, axis=1)

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [71]:
np.insert(a, 0, 5, axis=1)

array([[5, 1, 1],
       [5, 2, 2],
       [5, 3, 3]])

In [72]:
np.insert(a, 1, 5, axis=0)

array([[1, 1],
       [5, 5],
       [2, 2],
       [3, 3]])

In [73]:
np.insert(a, 0, 5, axis=0)

array([[5, 5],
       [1, 1],
       [2, 2],
       [3, 3]])

In [30]:
np.insert(a, 3, 5, axis=0)

array([[1, 1],
       [2, 2],
       [3, 3],
       [5, 5]])

In [74]:
a = np.array([[1, 1], [2, 2], [3, 3]])
print(a)

[[1 1]
 [2 2]
 [3 3]]


In [75]:
np.insert(a, [1], [[4],[5],[6]], axis=1)

array([[1, 4, 1],
       [2, 5, 2],
       [3, 6, 3]])

In [76]:
np.insert(a, [1], [4,5,6], axis=1)

array([[1, 4, 5, 6, 1],
       [2, 4, 5, 6, 2],
       [3, 4, 5, 6, 3]])

In [77]:
np.insert(a, 1, [[4],[5],[6]], axis=1)

array([[1, 4, 5, 6, 1],
       [2, 4, 5, 6, 2],
       [3, 4, 5, 6, 3]])

In [78]:
np.array_equal(np.insert(a, 1, [1, 2, 3], axis=1),
               np.insert(a, [1], [[1],[2],[3]], axis=1))

True

In [79]:
np.insert(a, 1, [4,5,6], axis=1)

array([[1, 4, 1],
       [2, 5, 2],
       [3, 6, 3]])

In [80]:
b = np.array([1, 1, 2, 2, 3, 3])
np.insert(b, slice(2, 4), [5, 6])  # slice() methodu ; slice(start, stop, end) 
                                   # end dahil değildir.

array([1, 1, 5, 2, 6, 2, 3, 3])

In [55]:
print(b)

[1 1 2 2 3 3]


In [56]:
np.insert(b, [2, 2], [5, 6])

array([1, 1, 5, 6, 2, 2, 3, 3])

In [57]:
np.insert(b, 2, [5, 6])

array([1, 1, 5, 6, 2, 2, 3, 3])

In [61]:
a = np.array([[1, 1], [2, 2], [3, 3]])
print(a)

[[1 1]
 [2 2]
 [3 3]]


In [82]:
np.insert(a, 1, [5, 6])  # axis belirtmediğimiz için flattened çalışacaktır.

array([1, 5, 6, 1, 2, 2, 3, 3])

In [84]:
np.insert(a, [1], [5, 6])

array([1, 5, 6, 1, 2, 2, 3, 3])

In [85]:
np.array_equal(np.insert(a, 1, [5, 6]),
               np.insert(a, [1], [5, 6]) )

True

In [88]:
np.insert(a, [1], [[5], [6]], axis=0)

array([[1, 1],
       [5, 5],
       [6, 6],
       [2, 2],
       [3, 3]])

In [92]:
np.insert(a, 1, [[5], [6]], axis=0)

array([[1, 1],
       [5, 5],
       [6, 6],
       [2, 2],
       [3, 3]])

In [89]:
np.insert(a, 1, [5, 6], axis=0)

array([[1, 1],
       [5, 6],
       [2, 2],
       [3, 3]])

In [91]:
np.insert(a, 1, [[5], [6]], axis=1)

array([[1, 5, 6, 1],
       [2, 5, 6, 2],
       [3, 5, 6, 3]])

****
### delete( ) Methodu ile Array'den Eleman Silme

__Zorunlu parametreleri ; array ve obj__  
__syntax yapısı ; delete( array, obj, axis)__  
__obj parametresine silinecek indexler girilir. 
Yalnız burada girilen indexler çok-boyutlu arraylerde subarray(alt arrayler)'leri alır.__  

__axis parametresi opsiyoneldir.__  
__Default olarak; flattened(düzleştirilmiş-tek-boyutlu halde) bir array üretilir.__  
__Axis default haldeyken eleman silme yapılırken de indexler tek-boyutlu array halinde düşünülür.__  

In [95]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [100]:

np.delete(arr, 1) 

# axis değeri default alınacak. Dolayısıyla array, flattened olarak alınır ve öyle işlem yapılır.
# obj'ye girilen index değeri 1 olduğu için silinecek eleman "2" değeri olur.

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [129]:

np.delete(arr, 1, axis=1)

# axis 1 olduğu için bu eksendeki subarray silinecek. 
# obj 1 olduğu için bu indexteki subarray siliniyor.

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [104]:

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [105]:

np.delete(arr, [1, 3, 5])

array([ 1,  3,  5,  7,  8,  9, 10, 11, 12])

In [106]:
np.delete(arr, [1, 1])

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [109]:

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [135]:

np.delete(arr, 1, axis=1)
#axis-1 de 1 nolu indexteki subarray [2,6,10] olur ve bu subarray silinir.

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [125]:
np.delete(arr, [1], axis=1)

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [122]:

np.delete(arr, [1,1], axis=1)

#axis-1 de [1,1] indexindeki subarray [2,6,10] olur ve bu subarray silinir.

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [123]:
np.array_equal(np.delete(arr, [1,1], axis=1),
               np.delete(arr, [1], axis=1) )

True

In [126]:

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [131]:
np.delete(arr, [0, 1], axis=1)

# axis-1'de 0 nolu indexteki subarray ; [1, 5, 9]
# axis-1'de 1 nolu indexteki subarray ; [2, 6, 10]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [132]:

np.delete(arr, [0, 2], axis=1)

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [137]:

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [136]:

np.delete(arr, 1, axis=0)  

# axis değeri 0 olduğu için obj'ye girilen index değerindeki subarray alınır.
# obj değeri 1 ; ve 1 nolu indexte subarray olarak [5,6,7,8] bulunuyor.
# [5,6,7,8] subarray'i silinecektir.

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [142]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [143]:
np.delete(arr, [0, 1], axis=0)

array([[ 9, 10, 11, 12]])

# Slicing Arrays | Arraylar'i Parçalara Ayırma İşlemi

**>> Slicing arrays ;
Verilen bir index numarasından bir diğerine kadar array elemanlarını alma işlemidir.**

**Syntax ;**    
****
**array[start:stop]**
****    
    ya da 
****    
**array[start:stop:step]**
****   
    şeklindedir.

**Start değeri için default(varsayılan) değer : 0** 

**Stop değeri için default(varsayılan) değer : arrayin maximum index değeridir(son elemanın indexi)**

**Step değeri için default(varsayılan) değer : 1**

**Örnek :**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr[0:8]   # İlk indeksten başlar 8. index'e kadar alır ; 8. index dahil değildir...!

array([1, 2, 3, 4, 5, 6, 7])

**|--> 8. index'e kadar aldığı için en son 7. indexi almış oldu böylece bütün array'i aldı.
  Step değeri belirtmediğimiz için default step değerini aldı, yani 1'er 1'er artırdı.**

In [25]:
arr[0:8:1]

array([1, 2, 3, 4, 5, 6, 7])

In [194]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7])

**|--> Step değerini belirterek bu şekilde de aynı sonucu elde edebiliriz...**

In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[2:]

array([3, 4, 5, 6, 7])

**|--> Start değerini belirttik, 2 numaralı indexten başladı. 
       Stop değerini vermediğimiz için array'in son elemanına kadar aldı,
       Step değerini vermediğimiz için default olarak 1'er 1'er artırdı...**

In [47]:
arr[:8]

array([1, 2, 3, 4, 5, 6, 7])

**|--> Start değerini vermedik, 0 numaralı indexten başladı. 
       Stop değerini verdik, 8'e kadar aldı, 8 dahil değil..!
       Step değerini vermediğimiz için default olarak 1'er 1'er artırdı...**

In [49]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7])

In [50]:
arr[::]

array([1, 2, 3, 4, 5, 6, 7])

**arr[:] kullanımı array[start:stop] syntax'ına,
  arr[::] kullanımı array[start:stop:step] syntax'ına uygun oldukları için
  hiçbir değer girilmediği durumlarda default değerleri alarak bütün array'i verdi...!**

In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [9]:
arr[4:]            #arr[1, 2, 3, 4, 5, 6, 7]

array([5, 6, 7])

In [10]:
arr[:4]            #arr[1, 2, 3, 4, 5, 6, 7]

array([1, 2, 3, 4])

In [11]:
arr[1:3]           #arr[1, 2, 3, 4, 5, 6, 7]

array([2, 3])

In [16]:
arr[1:-1]          # arr[1, 2, 3, 4, 5, 6, 7]
                # 1.indexten başladı, -1. indexe kadar aldı -1.index dahil değil
                # yani son eleman olan "7" yi almadı.

array([2, 3, 4, 5, 6])

In [18]:
arr[1:-3]           # arr[1, 2, 3, 4, 5, 6, 7]

array([2, 3, 4])

In [13]:
arr[::2]           #arr[1, 2, 3, 4, 5, 6, 7]

array([1, 3, 5, 7])

In [14]:
arr[-1:]           #arr[1, 2, 3, 4, 5, 6, 7]

array([7])

In [15]:
arr[-1::-1]              #arr[1, 2, 3, 4, 5, 6, 7]

array([7, 6, 5, 4, 3, 2, 1])

****
**|-->Array'i parçalayıp bir başka variable'a atamasını yapabilir,
ve farklı bir array olarak kullanabiliriz; veya atama yapmadan doğrudan bir 
kontrol ifadesi içinde ya da başka bir yerde kullanabiliriz.**

**Örnekler :**

In [57]:
arr = np.array([1,2,3,4,5,6,7])

new_arr = arr[1:3]

print(new_arr)

[2 3]


In [61]:
x = 6

if x in arr[1:4] :
    print("if bloğuna girdik.")
    
elif x in arr[3:8]:
    print("elseif bloğuna girdik.")

elseif bloğuna girdik.


***

## 2-D Arrayleri Parçalara Ayırma | Slicing 2-D Arrays

**Eğer birden fazla boyuta sahip (2-D veya 3-D) arraylerde eleman erişimini**

**doğru anladıysanız bu arraylerde parçalara ayırma işlemini de kolayca yapabilirsiniz.**

****

In [47]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


**Açıklama :**

**arr[a,b] de girilen ilk değer yani a değeri 1 olduğu için**

**arrayin 1 index numaralı elemanına yani [6, 7, 8, 9, 10] arrayine gitti.**

**arr[a,b] de b değeri 1:4 olduğu için a ile gidilen [6, 7, 8, 9, 10] arrayinde;**

**1 num. index ten 4 numaralı index'e kadar (4 dahil değil) elemanları seçmiş olur.**

**Sonuç [7, 8, 9] olur.**

****

In [49]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


****

<b>Açıklama :  

<b>arr[0:2, 2] ifadesinde ilk index değeri 0:2 olduğu için ;  

<b>0 ve 1 nolu elementleri seçtik yani ;  

<b>[1, 2, 3, 4, 5] ve [6, 7, 8, 9, 10] arraylerini seçtik.  

<b>arr[0:2, 2] ifadesinde ikinci index değeri 2 olduğu için ;  

<b>İlk index değeriyle(0:2) seçtiğimiz [1, 2, 3, 4, 5] ve [6, 7, 8, 9, 10] arraylerinde ;

<b>2 index numarasında olan elemanları seçer. Dolayısıyla ;  

<b>[1, 2, 3, 4, 5] arrayinde 2 numaralı indexte 3 değeri var.  

<b>[6, 7, 8, 9, 10] arrayinde 2 numaralı indexte 8 değeri var.  

<b>Sonuç [3,8] olur.

****

In [50]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


****

# NumPy Data Tipleri ve Array Tipleri | Data Types - Array Types

**NumPy'de bazı Data Tipleri ve gösterim sembolleri :**

__i - integer  
b - boolean  
f - float  
S - string__

## Bir Arrayin Tipini Kontrol Etme | Checking the Data Type of an Array

__NumPy nin "dtype" attribute'ü bir arrayin tipini tutar.  
Hem bir arrayin tipini görmek için hem de tip belirlemede kullanılabilir.__

In [54]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr.dtype)

int32


In [53]:
f_array = np.array([0, .5, 1, 1.5, 2])

print(f_array.dtype)

float64


In [55]:
s_arr = np.array(['apple', 'banana', 'cherry'])

print(s_arr.dtype)

<U6


In [57]:

new_arr = np.array([1, 2, 3, 4], dtype='S')

print(new_arr)  
print(new_arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [64]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [63]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [60]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i8')

print(arr)
print(arr.dtype)

[1 2 3 4]
int64


In [176]:
import sys
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='int32')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [61]:

f_arr = np.array([1, 2, 3], dtype='f')

print(f_arr)  
print(f_arr.dtype)

[1. 2. 3.]
float32


## Array'in Data Tipini Değiştirmek

__Bir array'in data tipini değiştirmek için astype() methodu kullanılır.  
astype() methodu parametre olarak belirlenen string bir data tipi ifadesi alır.  
Örneğin; integer için 'i', float için 'f' gibi.__  


__Örnekler :__

In [69]:
arr = np.array([1, 2, 3, 4, 5])

arr = arr.astype('f')

print(arr.dtype)
print(arr)

float32
[1. 2. 3. 4. 5.]


In [70]:
arr = arr.astype('float64')

print(arr.dtype)
print(arr)

float64
[1. 2. 3. 4. 5.]


In [74]:

arr = np.array([1.1, 2.7, 3.5])

newarr = arr.astype('i')  # Mevcut bir Arrayin tipini değiştirip başka bir variable'a  
                          # atamasını yaparak yeni bir array de oluşturabiliriz...
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [75]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [179]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Output:
# [[ 1  2  20  4  5]
# [ 6  7 20  9 10]]


In [180]:

a[:, 2] = 20
print(a)

[[ 1  2 20  4  5]
 [ 6  7 20  9 10]]


# NumPy Array'lerde Copy() Methodu ile Array Kopyalama

__NumPy'de bir array, copy() methodu ile kopyalanabilir.  
copy() methodu ile kopyalanan array ve orjinal array birbirinden ayrı olur.  
Yani orjinal arrayde yapılan değişiklik kopyalanmış arrayi etkilemez.__

__Örnekler :__

In [76]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [77]:
x[2] = 16

print(arr)
print(x)

[42  2  3  4  5]
[ 1  2 16  4  5]


## View() Methodu ve Copy() Methodu ile Farkı

__view() methodu ile bir array kopyalanırsa orjinal arrayde  
yapılacak bir değişiklik kopyalanmış arrayi de etkiler, değiştirir.__

In [78]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# Shape of an Array

__Bir arrayin biçimi "shape" ile ifade edilir.  
Ve aynı isimdeki attribute ile shape değeri tutulmaktadır.  
Shape ; herbir boyuttaki eleman sayısı demektir.__  
  
__Örnekler :__

In [79]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [84]:
new_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(new_arr.shape)

(2, 2, 3)


# NumPy Array Reshaping | Arraylerde Reshape İşlemi (Yeniden Biçimlendirme)

__Reshaping-Reshape İşlemi ; bir arrayin biçimini(shape) değiştirir.  
Bir arrayin biçimi(shape) ise ; herbir boyuttaki elemanların sayısıdır.  
Reshape işlemi :  
        -Boyut ekleme  
        -Boyut azaltma  
        -Herbir boyuttaki elemanların sayısını değiştirme  
        yöntemleriyle yapılabilir.__
        

__Bu işlem reshape() methodu kullanılarak yapılır.__

__Örnekler :__

__1-D Array'den 2-D array'e Dönüştürme Örneği :__

In [90]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new_arr = arr.reshape(4, 3)

print(arr, '\n')
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [96]:
print(arr.ndim)     #ndim attribute ile array'in boyut sayısını buluyoruz.
print(new_arr.ndim)

1
2


****
__1-D Array'den 3-D array'e Dönüştürme Örneği :__

In [98]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new_arr = arr.reshape(2, 3, 2)

print(arr, '\n')
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [99]:
print(arr.ndim)     #ndim attribute ile array'in boyut sayısını buluyoruz.
print(new_arr.ndim)

1
3


****
__Bilinmeyen Boyut :__

__Reshape işlemi yaparke, 1 tane bilinmeyen boyuta sahip olmanıza izin verilir.  
Yani 3-D array'e dönüşüm yapacaksanız 1 bilinmeyen boyut girişi yapabilirsiniz.  
Bu durumda bilinmeyen boyut için değer olarak -1 girilir, bu boyutu  
NumPy sizin yerinize hesaplayacaktır.__

In [104]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [105]:
print(arr.ndim)
print(new_arr.ndim)

1
3


****
__2-D arrayden 3-D array e reshape örneği:__

In [111]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


****
## resize( ) Methodu ile Shape Değiştirme

__resize methodu; reshape gibi array'in shape'ini değiştirmede kullanılır.    
Ancak reshape'ten farklı olarak ;    
Eğer yeni array, orjinal array'den daha büyükse, yeni array orjinal array'in    
kopyalarıyla doldurulur. Yani yeni array'in data sayısı farklı olur, data içeriği değişmiş olur.  
Böylece istenilen shape yeni array'e kazandırılmış olur.__

In [376]:
orgin_array = np.array([[0,1],[2,3]])

print(orgin_array)

[[0 1]
 [2 3]]


In [378]:

new_array = np.resize(orgin_array,(2,3))

print(new_array)

[[0 1 2]
 [3 0 1]]


In [379]:

orgin_array = np.array([[1,2],[3,4]])

print(orgin_array)

[[1 2]
 [3 4]]


In [385]:
new_array = np.resize(orgin_array,(2,3))

print(new_array)

[[1 2 3]
 [4 1 2]]


In [386]:
np.resize(orgin_array,(1,4))

array([[1, 2, 3, 4]])

In [387]:
np.reshape(orgin_array,(1,4))

array([[1, 2, 3, 4]])

In [388]:
np.resize(orgin_array,(2,4))

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [390]:
np.reshape(orgin_array,(1,4))
np.reshape(orgin_array,(2,4)) # reshape verilen shape'e göre data sayısını 
                              # artırma gibi bişey yapmaz. Orjinal data sayısı
                              # istenilen shape ile uyumlu değilse hata alırız.

ValueError: cannot reshape array of size 4 into shape (2,4)

## Flattening the Arrays | Çok-boyutlu Array'i Tek-boyutlu Array'e Dönüştürme

__Bu işlemi ;  
reshape( -1 )
ile yapabiliriz.__

In [112]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


### flatten( ) methodu ile

__Çok-boyutlu array'i tek-boyutlu array'e dönüştürmek için  
flatten() methodu da kullanılabilir.  
"order" parametresi ile sütun tabanlı(column-major) olarak da yapılabilir. 
Bunun için order = 'F' yapılır.  
"order" parametresinin default değeri satır temelli(row-major) olarak 'C' dir.__

In [354]:
a = np.array([[1,2], [3,4]])

print(a)


[[1 2]
 [3 4]]


In [358]:
flatten_array = a.flatten()  # order değeri default olarak row-major olduğu için
                             # satır satır okuyacak ve tek boyutta düzleştirecek. 
print(flatten_array)

[1 2 3 4]


In [359]:

flatten_array = a.flatten(order='F')  # order değeri column-major girildiği için
                                      # sütun sütun okuyacak ve tek boyutta düzleştirecek. 
print(flatten_array)

[1 3 2 4]


In [360]:

# Yeni Örnek :
    
b = np.array([[1,2], [3,4], [5,6]])
print(b)


[[1 2]
 [3 4]
 [5 6]]


In [361]:
flatten_array = b.flatten()  # order değeri default olarak row-major olduğu için
                             # satır satır okuyacak ve tek boyutta düzleştirecek. 
print(flatten_array)

[1 2 3 4 5 6]


In [363]:

flatten_array = b.flatten(order='F')  # order değeri column-major girildiği için
                                      # sütun sütun okuyacak ve tek boyutta düzleştirecek. 
print(flatten_array)

[1 3 5 2 4 6]


****
## flat Attribute ile Arraylerde Eleman Okuma

__flat attribute ; çok-boyutlu arraylerde tek boyutluymuş gibi indexleme  
yaparak eleman okumayı sağlar.__


In [365]:
x = np.arange(1, 7).reshape(2, 3)

print(x)

[[1 2 3]
 [4 5 6]]


In [366]:
# Bu arrayde 4 değerine ulaşmak (normalde) ;

print( x[1,0] )


4


In [367]:
# flatten ile ulaşırken ise ;

x.flat[3]    # arrayi tek boyutlu düşünürsek [1,2,3,4,5,6] da 
             # ulaşmak istenilen '4' değerinin index num. 3 olur.

4

****

# NumPy Array Iterating | Array'leri Döngülerde Kullanmak

In [129]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


In [115]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [116]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
i = 0
for x in arr:
    i= i+1
    print("Döngüye", i,". kez girdi...")
    print(x)

Döngüye 1 . kez girdi...
[1 2 3]
Döngüye 2 . kez girdi...
[4 5 6]


****

In [117]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


****

In [118]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


****

## Iterating Arrays Using nditer() | Arrayleri Döngüde nditer() Methodu ile Kullanmak

__nditer() methodu sayesinde iç içe for döngüsü yapmadan doğrudan her bir skaler eleman  
döngü elemanı olarak kullanılabilir.__ 

In [120]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [122]:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


# Joining NumPy Arrays | Arrayleri Birleştirmek

__İki farklı arrayi birleştirme işlemidir.  
concatenate() methodu ile yapılır.__

In [137]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


****

In [134]:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)


[[1 2 5 6]
 [3 4 7 8]]


In [135]:

arr.ndim

2

__axis parametresine hiçbir değer girmezsek varsayılan değeri 0 olur.  
axis değeri sıfırken satırlar dikey olarak birleştirilir.  
axis değeri 1 girilirse arrayler yatay olarak birleştirilir.__


In [139]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2))   #axis değeri 0 kabul edilir.

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


****
### Arrayleri Stack() Methodu ile Birleştirme

__Stack() methodu, elemanları üst üste yığma işlemi yaparak arrayleri birleştirir.__

In [140]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [142]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [143]:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [144]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.stack((arr1, arr2))

print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


****

# Splitting NumPy Arrays | Arrayleri Farklı Arrayler Olarak Bölmek

__array_split() methodu ile yapılır.  
Bir arrayi farklı arrayler olarak bölüp, bu arrayleri eleman olarak tutar.__

__Bir arrayi 3 parçaya bölelim :__

In [147]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)  # 3 parçaya böleceğimiz için parametreye 3 girdik. 

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


__Yukarıda görüldüğü gibi split / bölme işlemi sonucu 3 array içeren bir array aldık.__ 


In [149]:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)   # 4 parçaya bölüyoruz.

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


__Dikkat :  
    array_split() methodu yukarıdaki gibi eşit bölme için gereken eleman sayısı   
    yetersiz olduğunda eleman sayısını bölme sayısına göre ayarlar.__

****
__Bölme işlemi sonucu oluşan arraylere erişmek :__

In [151]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


****
__Çok-boyutlu arraylerde de aynı şekilde bölme işlemi yapılır :__

In [152]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [153]:
print(newarr[0])
print(newarr[1])
print(newarr[2])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


****

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Boolean arrays
_(Also called masks)_

In [82]:
a = np.arange(4)

In [83]:
a

array([0, 1, 2, 3])

In [85]:
a[0], a[-1]

(0, 3)

In [84]:
a[[0, -1]]

array([0, 3])

In [86]:
a[[True, False, False, True]]

array([0, 3])

In [89]:
a

array([0, 1, 2, 3])

In [88]:
a >= 2

array([False, False,  True,  True])

In [90]:
a[a >= 2]

array([2, 3])