In [2]:
import numpy as np

In [3]:
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [3]:
arr.shape

(2, 2)

In [4]:
arr.ndim

2

In [13]:
arr=np.array([1,2,3])
new_arr=np.append(arr,[[4,5,6],[7,8,9]])

In [14]:
new_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
new_arr.shape

(9,)

# 21 kasım 2022

Arraylarda arama yapma (where() metodu)

In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,4,4])

In [8]:
x=np.where((arr==4))
x

(array([3, 5, 6], dtype=int64),)

In [13]:
x2=np.where((arr<= 2)&(arr%2==0))
x2

(array([1], dtype=int64),)

In [14]:
x3=np.where((arr<= 2)|(arr%2==0))
x3

(array([0, 1, 3, 5, 6], dtype=int64),)

# Numpy da rastgele sayı üretme methodları

In [16]:
from numpy import random

In [4]:
x=random.randint(100)
x

NameError: name 'random' is not defined

In [29]:
x=random.randint(1,10)
x

4

In [ ]:
x2=np.where((arr<= 2)&(arr%2==0))
x2

In [36]:
x=random.randint(2)
x

1

In [5]:
arr=np.random.randint(2,size=10)
arr

array([0, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [6]:
arr=np.random.randint(8,size=10)
arr

array([4, 1, 7, 0, 3, 3, 7, 6, 5, 2])

In [8]:
arr=np.random.randint(2,size=(3,4))
arr

array([[0, 1, 1, 1],
       [1, 0, 1, 0],
       [1, 1, 0, 1]])

In [12]:
arr=np.random.randint(3,size=(3,2,4))
arr

array([[[0, 2, 1, 2],
        [1, 0, 2, 1]],

       [[2, 2, 2, 2],
        [2, 1, 1, 1]],

       [[1, 2, 2, 2],
        [2, 0, 2, 0]]])

In [17]:
# rand() float sayılar uretir

from numpy import random
x=random.rand()
x

0.7762279750327218

In [19]:
x=np.random.rand(3,2) #(3,2) shape
x

array([[0.12068403, 0.34510818],
       [0.92440917, 0.88478045],
       [0.79454484, 0.08579814]])

In [20]:
x=np.random.rand(3,4,4)
x

array([[[0.61657641, 0.79831755, 0.53817081, 0.39277195],
        [0.96450774, 0.47399207, 0.33139315, 0.90128311],
        [0.22286487, 0.52479056, 0.30245915, 0.68988432],
        [0.18261744, 0.19429638, 0.83814626, 0.79077153]],

       [[0.77664499, 0.72489494, 0.02504468, 0.00699477],
        [0.90273424, 0.82277833, 0.61479854, 0.48730382],
        [0.74354812, 0.93319904, 0.35089619, 0.25472546],
        [0.13987245, 0.11627677, 0.850592  , 0.88952144]],

       [[0.68748643, 0.25798164, 0.71330277, 0.41695335],
        [0.92989119, 0.05942153, 0.84970472, 0.70165006],
        [0.1188909 , 0.85982011, 0.71591331, 0.21142494],
        [0.26691023, 0.11805221, 0.6844158 , 0.07826965]]])

In [22]:
# zeros() metodu
arr=np.zeros(3)
arr

array([0., 0., 0.])

In [23]:
arr=np.zeros(5,dtype='int')
arr

array([0, 0, 0, 0, 0])

In [25]:
arr=np.zeros((2,4),dtype='int')
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [32]:
arr=np.zeros((2,4,3),dtype=bool)
arr

array([[[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]]])

In [34]:
# zeros_like() metodu
arr=np.arange(48).reshape(3,4,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [35]:
arr2=np.zeros_like(arr)
arr2

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [36]:
arr2.shape

(3, 4, 4)

In [37]:
# ones() metodu
arr=np.ones(3)
arr

array([1., 1., 1.])

In [40]:
# ones() metodu
arr=np.ones(5,dtype=int)
arr

array([1, 1, 1, 1, 1])

In [41]:
# ones() metodu
arr=np.ones((2,3,3),dtype=int)
arr

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [42]:
# ones_like() metodu
arr=np.arange(48).reshape(3,4,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [43]:
arr2=np.ones_like(arr)
arr2

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [51]:
# eye()

arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
# eye()

arr=np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])